### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by deepthi237** [coldKnight/TrafficLight_Detection-TensorFlowAPI#3]
python data_conversion_udacity_sim.py /Users/ppatil2/Documents/dataset sim_data.record
/Users/ppatil2/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "data_conversion_udacity_sim.py", line 104, in <module>
    tf.app.run()
  File "/Users/ppatil2/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "data_conversion_udacity_sim.py", line 76, in main
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
  File "/Users/ppatil2/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 111, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "/Users/ppatil2/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

When I am trying to create TFR record files, I am getting this error. Please advice on how to proceed? 
I have been trying to setup the tensorflow framework for detecting traffic lights and are stuck with the above error.

**Comment by coldKnight** [comment]
Hi,
There are two places where a similar issue has been raised.
1. https://github.com/tensorflow/models/issues/3762
2. https://github.com/tensorflow/models/issues/3954

Can you refer to them and let me know if the issues were resolved?

**Comment by TramBao2000** [comment]
2022-04-07 03:17:21.018332: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0407 03:17:21.020073 140568950208384 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0407 03:17:21.021467 140568950208384 mirrored_strategy.py:376] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Traceback (most recent call last):
  File "./object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "./object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/content/drive/MyDrive/Colab Notebooks/sohoa_cmnd_text/models/research/object_detection/model_lib_v2.py", line 488, in train_loop
    pipeline_config_path, config_override=config_override)
  File "/content/drive/MyDrive/Colab Notebooks/sohoa_cmnd_text/models/research/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 81, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

I'm helpless, someone help me !!!
